name: Deploy to github page

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Action checkout
        uses: actions/checkout@v5

      - name: Action setup node
        uses: actions/setup-node@v5
        with:
          node-version: latest
          cache: npm

      - name: Clean install dependencies
        run: npm ci

      - name: Building for production
        run: npm run build
        env:
          VITE_BASE: '/zypheris/'

      - name: Deploy to github page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
